//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mindafy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activity()
        {
            this.Conforms = new HashSet<Conforms>();
            this.insert = new HashSet<insert>();
        }
    
        public int id_Activity { get; set; }
        public Nullable<System.DateTime> start_Date_Activity { get; set; }
        public Nullable<System.DateTime> end_Date_Activity { get; set; }
        public string description_Activity { get; set; }
        public string name_Activity { get; set; }
        public Nullable<bool> state { get; set; }
        public Nullable<double> Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conforms> Conforms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<insert> insert { get; set; }
    }
}
